name: CI - Dockerized API Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
permissions:
  contents: write

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image (builds and runs tests inside)
        run: docker build -t sayedo/restassured-test:latest .

      - name: Push Docker image
        run: docker push sayedo/restassured-test:latest

      - name: Copy Allure results from container
        run: |
          docker create --name test-container sayedo/restassured-test:latest
          docker cp test-container:/app/allure-results ./allure-results
          docker rm test-container

      - name: Install Allure CLI
        run: |
          wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.0/allure-commandline-2.24.0.zip
          unzip allure-commandline-2.24.0.zip -d allure-cli
          sudo ln -s $PWD/allure-cli/allure-2.24.0/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        run: |
          allure generate ./allure-results -o ./allure-report --clean

      - name: List Allure Report files
        run: ls -la ./allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          force_orphan: true
          enable_jekyll: false
