name: CI - Dockerized API Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image (builds and runs tests inside)
        run: docker build -t sayedo/restassured-test:latest .

      - name: Push Docker image
        run: docker push sayedo/restassured-test:latest

      - name: Generate Allure report inside container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/allure-results:/project/allure-results \
            -v ${{ github.workspace }}/allure-report:/project/allure-report \
            sayedo/restassured-test:latest bash -c "
              allure generate /project/allure-results -o /project/allure-report --clean
            "

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
