name: test-api

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      IMAGE_NAME: restassured-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_HUB_USER/$IMAGE_NAME:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push $DOCKER_HUB_USER/$IMAGE_NAME:latest

      - name: Run tests in Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/allure-results:/project/allure-results \
            $DOCKER_HUB_USER/$IMAGE_NAME:latest

      - name: Generate Allure Report
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/allure-results:/app/allure-results \
            -v ${{ github.workspace }}/allure-report:/app/allure-report \
            frankescobar/allure-docker-service:latest \
            generate /app/allure-results -o /app/allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
