name: CI - Dockerized API Tests with Allure and GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t sayedo/restassured-test:latest .

      - name: Push Docker image
        run: docker push sayedo/restassured-test:latest

      - name: Run tests and generate Allure report
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/allure-results:/project/allure-results \
            -v ${{ github.workspace }}/allure-report:/project/allure-report \
            sayedo/restassured-test:latest bash -c "
              mvn test &&
              allure generate /project/allure-results -o /project/allure-report --clean
            "

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
